// ============================================================
// PROYECTO EDTECH — MONGODB ATLAS
// Archivo 2: Datos de muestra — 3 colecciones
// BD: edtech | Ejecutar en Shell de Compass (EdTech2026)
// ============================================================

use("edtech");

// ============================================================
// 1. FORO_HILOS (30 documentos)
// ============================================================
db.foro_hilos.insertMany([
  { titulo: "¿Cómo funciona el event loop en JS?",        contenido: "Tengo dudas sobre cómo JavaScript maneja la asincronía internamente.",           id_alumno: 1,  id_curso: 1,  etiquetas: ["javascript","async"],          likes: 5,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 3,  contenido: "El event loop procesa la call stack y la callback queue en ciclos.", likes: 2, fecha: new Date() }] },
  { titulo: "Error al conectar Oracle con Node.js",       contenido: "Me sale ORA-12514 al intentar conectar node-oracledb, ¿alguien lo resolvió?",    id_alumno: 2,  id_curso: 5,  etiquetas: ["oracle","nodejs","error"],      likes: 8,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 5,  contenido: "Revisa que el servicio pdb_edtech esté abierto con ALTER PLUGGABLE DATABASE.", likes: 4, fecha: new Date() }, { id_alumno: 9, contenido: "También puede ser el tnsnames.ora, revísalo.", likes: 1, fecha: new Date() }] },
  { titulo: "¿Figma o Adobe XD para el proyecto?",        contenido: "Estoy dudando qué herramienta usar para los mockups del proyecto.",              id_alumno: 3,  id_curso: 3,  etiquetas: ["diseño","figma","ux"],          likes: 3,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "Diferencia entre UNION y JOIN",              contenido: "¿Cuándo uso UNION y cuándo JOIN en Oracle? Me confundo.",                        id_alumno: 4,  id_curso: 5,  etiquetas: ["oracle","sql"],                 likes: 11, fecha_creacion: new Date(), respuestas: [{ id_alumno: 1,  contenido: "JOIN combina columnas de dos tablas. UNION apila filas de dos queries.", likes: 6, fecha: new Date() }] },
  { titulo: "Recursos para aprender Cisco CCNA",          contenido: "¿Qué material extra recomiendan para preparar el CCNA?",                         id_alumno: 5,  id_curso: 7,  etiquetas: ["redes","cisco","ccna"],         likes: 7,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 12, contenido: "Packet Tracer de Cisco es gratuito y muy completo.", likes: 3, fecha: new Date() }] },
  { titulo: "MongoDB Atlas no me deja insertar",          contenido: "Me sale error de validación al insertar en foro_hilos, ¿por qué?",               id_alumno: 6,  id_curso: 6,  etiquetas: ["mongodb","error","atlas"],      likes: 4,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 8,  contenido: "Revisa que los campos required estén en tu documento.", likes: 2, fecha: new Date() }] },
  { titulo: "¿Para qué sirve el Aggregation Pipeline?",  contenido: "Vi el tema en clase pero no entendí su utilidad práctica.",                       id_alumno: 7,  id_curso: 6,  etiquetas: ["mongodb","aggregation"],       likes: 9,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 2,  contenido: "Es como el GROUP BY y JOINs de SQL pero para MongoDB, muy poderoso.", likes: 5, fecha: new Date() }] },
  { titulo: "Cómo hacer un buen pitch de startup",        contenido: "¿Qué estructura recomiendan para el pitch del curso de emprendimiento?",          id_alumno: 8,  id_curso: 12, etiquetas: ["startup","pitch","negocio"],    likes: 6,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "pandas vs numpy, ¿cuándo uso cada uno?",     contenido: "Ambos se usan en Data Science pero no tengo claro las diferencias.",              id_alumno: 9,  id_curso: 9,  etiquetas: ["python","pandas","numpy"],     likes: 12, fecha_creacion: new Date(), respuestas: [{ id_alumno: 15, contenido: "NumPy para operaciones matemáticas en arrays. Pandas para datos tabulares.", likes: 7, fecha: new Date() }] },
  { titulo: "¿Machine Learning sin matemáticas?",         contenido: "¿Se puede aprender ML sin saber cálculo y álgebra lineal?",                      id_alumno: 10, id_curso: 10, etiquetas: ["ml","matematicas"],            likes: 14, fecha_creacion: new Date(), respuestas: [{ id_alumno: 5,  contenido: "Puedes empezar con las librerías, pero para entender a fondo necesitas la base matemática.", likes: 8, fecha: new Date() }] },
  { titulo: "SEO vs SEM, diferencias clave",              contenido: "Me cuesta diferenciar ambas estrategias en el curso.",                            id_alumno: 11, id_curso: 11, etiquetas: ["marketing","seo","sem"],       likes: 5,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "React hooks vs class components",            contenido: "¿Sigue siendo relevante aprender class components o solo hooks?",                 id_alumno: 12, id_curso: 2,  etiquetas: ["react","hooks","javascript"],   likes: 10, fecha_creacion: new Date(), respuestas: [{ id_alumno: 7,  contenido: "Solo hooks. Los class components son legacy, ya nadie los usa en proyectos nuevos.", likes: 6, fecha: new Date() }] },
  { titulo: "¿Cómo exportar la BD Oracle para la rúbrica?", contenido: "El profesor pide exportar la BD, ¿cómo se hace en SQL Developer?",            id_alumno: 13, id_curso: 5,  etiquetas: ["oracle","exportar","rubrica"],  likes: 7,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 3,  contenido: "Tools > Database Export en SQL Developer. Selecciona tu esquema edtech_admin.", likes: 4, fecha: new Date() }] },
  { titulo: "Tailwind v4 no carga estilos",               contenido: "Instalé Tailwind v4 pero los estilos no se aplican en React.",                   id_alumno: 14, id_curso: 2,  etiquetas: ["tailwind","react","css"],      likes: 9,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 1,  contenido: "En v4 usa @import 'tailwindcss' en tu CSS principal, no las directivas antiguas.", likes: 5, fecha: new Date() }] },
  { titulo: "¿Qué es un índice compuesto en MongoDB?",    contenido: "Vi que se puede crear índice en dos campos, ¿para qué sirve?",                   id_alumno: 15, id_curso: 6,  etiquetas: ["mongodb","indices"],          likes: 6,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "Diferencia entre PDB y CDB en Oracle",       contenido: "En el laboratorio usamos CDB y PDB pero no entiendo bien la jerarquía.",         id_alumno: 16, id_curso: 5,  etiquetas: ["oracle","pdb","cdb"],          likes: 8,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 4,  contenido: "CDB es el motor completo (XE). La PDB es tu base de datos dentro del motor.", likes: 5, fecha: new Date() }] },
  { titulo: "JWT vs Sessions, ¿cuál es mejor?",           contenido: "Para autenticación en el proyecto, ¿qué conviene más?",                          id_alumno: 17, id_curso: 2,  etiquetas: ["auth","jwt","nodejs"],         likes: 13, fecha_creacion: new Date(), respuestas: [{ id_alumno: 7,  contenido: "JWT para APIs REST stateless. Sessions para apps tradicionales con servidor.", likes: 7, fecha: new Date() }] },
  { titulo: "Cómo hacer un MVP rápido",                   contenido: "¿Cuánto tiempo debería tomar hacer un MVP para una startup tech?",               id_alumno: 18, id_curso: 12, etiquetas: ["startup","mvp"],               likes: 5,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "Visualización de datos con matplotlib",      contenido: "¿Hay alguna forma más fácil de hacer gráficos bonitos en Python?",               id_alumno: 19, id_curso: 9,  etiquetas: ["python","visualizacion"],     likes: 4,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 10, contenido: "Prueba Seaborn, está sobre matplotlib pero con estilos mucho mejores.", likes: 3, fecha: new Date() }] },
  { titulo: "¿Cómo funciona bcrypt?",                     contenido: "El proyecto usa bcrypt para contraseñas, ¿alguien lo explica sencillo?",          id_alumno: 20, id_curso: 2,  etiquetas: ["seguridad","bcrypt","auth"],   likes: 10, fecha_creacion: new Date(), respuestas: [{ id_alumno: 1,  contenido: "bcrypt hace un hash irreversible con un salt aleatorio. Nunca guardas la contraseña real.", likes: 6, fecha: new Date() }] },
  { titulo: "VLANs en Packet Tracer",                     contenido: "No me funciona la configuración de VLANs en el simulador.",                      id_alumno: 21, id_curso: 7,  etiquetas: ["redes","vlan","cisco"],        likes: 3,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "Overfitting en Random Forest",               contenido: "Mi modelo tiene 99% en training y 60% en test, ¿qué hago?",                      id_alumno: 22, id_curso: 10, etiquetas: ["ml","overfitting"],            likes: 11, fecha_creacion: new Date(), respuestas: [{ id_alumno: 5,  contenido: "Reduce max_depth o aumenta min_samples_split. También prueba más datos.", likes: 6, fecha: new Date() }] },
  { titulo: "Google Ads con presupuesto bajo",            contenido: "¿Vale la pena usar Google Ads con solo 50 soles al día?",                        id_alumno: 23, id_curso: 11, etiquetas: ["marketing","ads"],             likes: 7,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 11, contenido: "Sí, con buena segmentación puedes tener ROI positivo.", likes: 4, fecha: new Date() }] },
  { titulo: "Mongoose vs driver nativo MongoDB",          contenido: "Para el backend del proyecto, ¿uso Mongoose o el driver oficial?",               id_alumno: 24, id_curso: 6,  etiquetas: ["mongodb","mongoose","nodejs"],  likes: 8,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 3,  contenido: "Mongoose para proyectos con esquema definido. Driver nativo si necesitas más control.", likes: 4, fecha: new Date() }] },
  { titulo: "¿Qué hace exactamente un tablespace?",       contenido: "Lo creamos en el lab pero no entiendo bien su función.",                         id_alumno: 25, id_curso: 5,  etiquetas: ["oracle","tablespace"],         likes: 6,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 16, contenido: "Es el espacio físico en disco donde Oracle guarda los datos.", likes: 3, fecha: new Date() }] },
  { titulo: "Cómo limpiar datos con pandas",              contenido: "Tengo un CSV con valores nulos y duplicados, ¿por dónde empiezo?",               id_alumno: 26, id_curso: 9,  etiquetas: ["python","pandas","limpieza"],  likes: 9,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 19, contenido: "dropna() para nulos, drop_duplicates() para duplicados.", likes: 5, fecha: new Date() }] },
  { titulo: "¿Ethical hacking es legal en Perú?",         contenido: "Para practicar pentesting, ¿hay algún marco legal que deba conocer?",            id_alumno: 27, id_curso: 8,  etiquetas: ["seguridad","legal","hacking"],  likes: 15, fecha_creacion: new Date(), respuestas: [{ id_alumno: 4,  contenido: "Solo en entornos propios o con autorización escrita. La Ley 30096 regula esto.", likes: 9, fecha: new Date() }] },
  { titulo: "Vectores en Illustrator para web",           contenido: "¿En qué formato exporto los íconos para que no pierdan calidad?",               id_alumno: 28, id_curso: 4,  etiquetas: ["diseño","svg","illustrator"],   likes: 4,  fecha_creacion: new Date(), respuestas: [] },
  { titulo: "Componentes Shadcn/ui con Tailwind v4",      contenido: "¿Shadcn/ui ya es compatible con Tailwind v4 o toca esperar?",                   id_alumno: 29, id_curso: 2,  etiquetas: ["react","shadcn","tailwind"],   likes: 7,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 14, contenido: "Sí, desde 2025 Shadcn soporta v4. Solo sigue la guía oficial.", likes: 4, fecha: new Date() }] },
  { titulo: "Cómo hacer una regresión lineal simple",     contenido: "¿Cuál es el mínimo de código en Python para hacer una regresión?",              id_alumno: 30, id_curso: 10, etiquetas: ["ml","python","regresion"],     likes: 8,  fecha_creacion: new Date(), respuestas: [{ id_alumno: 22, contenido: "from sklearn.linear_model import LinearRegression — con 5 líneas tienes tu modelo.", likes: 5, fecha: new Date() }] }
]);


// ============================================================
// 2. PROGRESO_ALUMNO (30 documentos)
// ============================================================
db.progreso_alumno.insertMany([
  { id_alumno: 1,  id_curso: 1,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 1, completada: true,  fecha_completada: new Date(), apuntes: "let vs const — siempre const por defecto" }, { id_leccion: 2, completada: true,  fecha_completada: new Date(), apuntes: "Arrow functions no tienen su propio this" }, { id_leccion: 3, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 1,  id_curso: 5,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 13, completada: true,  fecha_completada: new Date(), apuntes: "CDB contiene múltiples PDBs" }, { id_leccion: 14, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 15, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 2,  id_curso: 3,  porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 7,  completada: true,  fecha_completada: new Date(), apuntes: "Regla 60-30-10 para colores" }, { id_leccion: 8,  completada: true,  fecha_completada: new Date(), apuntes: "Wireframe primero, prototipo después" }, { id_leccion: 9,  completada: true,  fecha_completada: new Date(), apuntes: "Design system = consistencia" }] },
  { id_alumno: 2,  id_curso: 9,  porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 25, completada: true,  fecha_completada: new Date(), apuntes: "df.dropna() elimina filas con nulos" }, { id_leccion: 26, completada: true,  fecha_completada: new Date(), apuntes: "plt.show() al final" }, { id_leccion: 27, completada: true,  fecha_completada: new Date(), apuntes: "Correlación != causalidad" }] },
  { id_alumno: 3,  id_curso: 2,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 4,  completada: true,  fecha_completada: new Date(), apuntes: "Props son inmutables" }, { id_leccion: 5,  completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 6,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 3,  id_curso: 6,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 16, completada: true,  fecha_completada: new Date(), apuntes: "Embeber cuando los datos se leen juntos siempre" }, { id_leccion: 17, completada: true,  fecha_completada: new Date(), apuntes: "Índice en campo de búsqueda frecuente" }, { id_leccion: 18, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 4,  id_curso: 1,  porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 1,  completada: true,  fecha_completada: new Date(), apuntes: "Tipos primitivos vs objetos" }, { id_leccion: 2,  completada: true,  fecha_completada: new Date(), apuntes: "Closures para encapsular estado" }, { id_leccion: 3,  completada: true,  fecha_completada: new Date(), apuntes: "async/await sobre Promises" }] },
  { id_alumno: 4,  id_curso: 4,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 10, completada: true,  fecha_completada: new Date(), apuntes: "Bezier para curvas suaves" }, { id_leccion: 11, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 12, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 5,  id_curso: 7,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 19, completada: true,  fecha_completada: new Date(), apuntes: "OSI: 7 capas, TCP/IP: 4 capas" }, { id_leccion: 20, completada: true,  fecha_completada: new Date(), apuntes: "enable -> configure terminal" }, { id_leccion: 21, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 5,  id_curso: 10, porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 28, completada: true,  fecha_completada: new Date(), apuntes: "y = mx + b en regresión lineal" }, { id_leccion: 29, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 30, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 6,  id_curso: 3,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 7,  completada: true,  fecha_completada: new Date(), apuntes: "Contraste mínimo WCAG 4.5:1" }, { id_leccion: 8,  completada: true,  fecha_completada: new Date(), apuntes: "Wireframe en papel primero" }, { id_leccion: 9,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 6,  id_curso: 11, porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 31, completada: true,  fecha_completada: new Date(), apuntes: "Keywords long tail" }, { id_leccion: 32, completada: true,  fecha_completada: new Date(), apuntes: "CTR = clics / impresiones" }, { id_leccion: 33, completada: true,  fecha_completada: new Date(), apuntes: "Publicar 3 veces/semana mínimo" }] },
  { id_alumno: 7,  id_curso: 2,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 4,  completada: true,  fecha_completada: new Date(), apuntes: "JSX es JS + HTML" }, { id_leccion: 5,  completada: true,  fecha_completada: new Date(), apuntes: "useEffect con [] solo corre al montar" }, { id_leccion: 6,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 7,  id_curso: 8,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 22, completada: true,  fecha_completada: new Date(), apuntes: "nmap -sV detecta versiones" }, { id_leccion: 23, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 24, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 8,  id_curso: 5,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 13, completada: true,  fecha_completada: new Date(), apuntes: "ALTER SESSION SET CONTAINER para cambiar PDB" }, { id_leccion: 14, completada: true,  fecha_completada: new Date(), apuntes: "PROCEDURE es reutilizable" }, { id_leccion: 15, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 8,  id_curso: 12, porcentaje_completado: 0.0,  ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 34, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 35, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 36, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 9,  id_curso: 1,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 1,  completada: true,  fecha_completada: new Date(), apuntes: "typeof null === object es bug histórico" }, { id_leccion: 2,  completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 3,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 9,  id_curso: 6,  porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 16, completada: true,  fecha_completada: new Date(), apuntes: "Embeber cuando se leen juntos" }, { id_leccion: 17, completada: true,  fecha_completada: new Date(), apuntes: "explain() para verificar índices" }, { id_leccion: 18, completada: true,  fecha_completada: new Date(), apuntes: "$group + $sum para totales" }] },
  { id_alumno: 10, id_curso: 9,  porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 25, completada: true,  fecha_completada: new Date(), apuntes: "isnull() detecta nulos" }, { id_leccion: 26, completada: true,  fecha_completada: new Date(), apuntes: "scatter plot para correlaciones" }, { id_leccion: 27, completada: true,  fecha_completada: new Date(), apuntes: "Pearson r va de -1 a 1" }] },
  { id_alumno: 10, id_curso: 2,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 4,  completada: true,  fecha_completada: new Date(), apuntes: "key prop evita re-renders en listas" }, { id_leccion: 5,  completada: true,  fecha_completada: new Date(), apuntes: "useState es asíncrono" }, { id_leccion: 6,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 11, id_curso: 4,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 10, completada: true,  fecha_completada: new Date(), apuntes: "Pen tool = control total" }, { id_leccion: 11, completada: true,  fecha_completada: new Date(), apuntes: "Logo en vector escala sin pixelar" }, { id_leccion: 12, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 12, id_curso: 7,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 19, completada: true,  fecha_completada: new Date(), apuntes: "192.168.x.x es privada" }, { id_leccion: 20, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 21, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 13, id_curso: 5,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 13, completada: true,  fecha_completada: new Date(), apuntes: "Un CDB puede tener hasta 252 PDBs" }, { id_leccion: 14, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 15, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 14, id_curso: 3,  porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 7,  completada: true,  fecha_completada: new Date(), apuntes: "Espaciado generoso = diseño limpio" }, { id_leccion: 8,  completada: true,  fecha_completada: new Date(), apuntes: "Prototipo interactivo en Figma" }, { id_leccion: 9,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 15, id_curso: 10, porcentaje_completado: 100.0, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 28, completada: true,  fecha_completada: new Date(), apuntes: "Sigmoid para clasificación binaria" }, { id_leccion: 29, completada: true,  fecha_completada: new Date(), apuntes: "n_estimators=100 buen punto de partida" }, { id_leccion: 30, completada: true,  fecha_completada: new Date(), apuntes: "F1-score mejor que accuracy en desbalanceadas" }] },
  { id_alumno: 16, id_curso: 1,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 1,  completada: true,  fecha_completada: new Date(), apuntes: "Hoisting mueve declaraciones al inicio del scope" }, { id_leccion: 2,  completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 3,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 17, id_curso: 6,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 16, completada: true,  fecha_completada: new Date(), apuntes: "_id es el índice primario por defecto" }, { id_leccion: 17, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 18, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 18, id_curso: 2,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 4,  completada: true,  fecha_completada: new Date(), apuntes: "Componente = función que retorna JSX" }, { id_leccion: 5,  completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 6,  completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 19, id_curso: 8,  porcentaje_completado: 33.3, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 22, completada: true,  fecha_completada: new Date(), apuntes: "Escanear solo en red propia o con permiso" }, { id_leccion: 23, completada: false, fecha_completada: null, apuntes: "" }, { id_leccion: 24, completada: false, fecha_completada: null, apuntes: "" }] },
  { id_alumno: 20, id_curso: 11, porcentaje_completado: 66.7, ultima_vez_visto: new Date(), lecciones_completadas: [{ id_leccion: 31, completada: true,  fecha_completada: new Date(), apuntes: "Keyword research con Google Keyword Planner" }, { id_leccion: 32, completada: true,  fecha_completada: new Date(), apuntes: "CTR = clics / impresiones" }, { id_leccion: 33, completada: false, fecha_completada: null, apuntes: "" }] }
]);


// ============================================================
// 3. MATERIALES_CURSO (36 documentos — 3 por curso)
// ============================================================
db.materiales_curso.insertMany([
  // Curso 1 — JavaScript
  { id_leccion: 1,  id_curso: 1,  tipo: "video", titulo: "Variables y tipos en JS",              url: "https://edtech.pe/videos/js-variables",       duracion_min: 55 },
  { id_leccion: 2,  id_curso: 1,  tipo: "pdf",   titulo: "Guía de funciones y closures",         url: "https://edtech.pe/pdf/js-funciones.pdf" },
  { id_leccion: 3,  id_curso: 1,  tipo: "quiz",  titulo: "Quiz: Asincronía en JS",               preguntas: [{ pregunta: "¿Qué devuelve una función async?", opciones: ["Un valor directo","Una Promise","undefined","Un callback"], respuesta_correcta: 1 }] },
  // Curso 2 — React + Node
  { id_leccion: 4,  id_curso: 2,  tipo: "video", titulo: "Componentes funcionales en React",     url: "https://edtech.pe/videos/react-componentes",   duracion_min: 75 },
  { id_leccion: 5,  id_curso: 2,  tipo: "pdf",   titulo: "Hooks: guía completa",                 url: "https://edtech.pe/pdf/react-hooks.pdf" },
  { id_leccion: 6,  id_curso: 2,  tipo: "quiz",  titulo: "Quiz: API REST con Express",           preguntas: [{ pregunta: "¿Qué método HTTP se usa para crear un recurso?", opciones: ["GET","POST","PUT","DELETE"], respuesta_correcta: 1 }] },
  // Curso 3 — UI/UX
  { id_leccion: 7,  id_curso: 3,  tipo: "video", titulo: "Principios de diseño visual",          url: "https://edtech.pe/videos/ux-principios",       duracion_min: 55 },
  { id_leccion: 8,  id_curso: 3,  tipo: "pdf",   titulo: "Guía de wireframing",                  url: "https://edtech.pe/pdf/wireframes.pdf" },
  { id_leccion: 9,  id_curso: 3,  tipo: "quiz",  titulo: "Quiz: Design Systems",                 preguntas: [{ pregunta: "¿Qué es un Design System?", opciones: ["Una plantilla HTML","Componentes y reglas de diseño reutilizables","Un tipo de prototipo","Un framework CSS"], respuesta_correcta: 1 }] },
  // Curso 4 — Illustrator
  { id_leccion: 10, id_curso: 4,  tipo: "video", titulo: "Herramientas de vector",               url: "https://edtech.pe/videos/ai-vectores",         duracion_min: 50 },
  { id_leccion: 11, id_curso: 4,  tipo: "pdf",   titulo: "Diseño de logotipos paso a paso",      url: "https://edtech.pe/pdf/logos.pdf" },
  { id_leccion: 12, id_curso: 4,  tipo: "quiz",  titulo: "Quiz: Exportación para web",           preguntas: [{ pregunta: "¿Qué formato es ideal para íconos web?", opciones: ["JPG","BMP","SVG","PSD"], respuesta_correcta: 2 }] },
  // Curso 5 — Oracle
  { id_leccion: 13, id_curso: 5,  tipo: "video", titulo: "Arquitectura CDB y PDB",               url: "https://edtech.pe/videos/oracle-arquitectura",  duracion_min: 85 },
  { id_leccion: 14, id_curso: 5,  tipo: "pdf",   titulo: "Manual de PL/SQL",                     url: "https://edtech.pe/pdf/plsql.pdf" },
  { id_leccion: 15, id_curso: 5,  tipo: "quiz",  titulo: "Quiz: Seguridad Oracle",               preguntas: [{ pregunta: "¿Qué hace GRANT CREATE SESSION?", opciones: ["Crea un usuario","Permite conectarse a la BD","Crea una tabla","Da rol DBA"], respuesta_correcta: 1 }] },
  // Curso 6 — MongoDB
  { id_leccion: 16, id_curso: 6,  tipo: "video", titulo: "Modelado de documentos",               url: "https://edtech.pe/videos/mongo-modelado",      duracion_min: 65 },
  { id_leccion: 17, id_curso: 6,  tipo: "pdf",   titulo: "Índices en MongoDB",                   url: "https://edtech.pe/pdf/mongo-indices.pdf" },
  { id_leccion: 18, id_curso: 6,  tipo: "quiz",  titulo: "Quiz: Aggregation Pipeline",           preguntas: [{ pregunta: "¿Qué hace $group?", opciones: ["Filtra documentos","Agrupa por un campo","Ordena resultados","Proyecta campos"], respuesta_correcta: 1 }] },
  // Curso 7 — Redes
  { id_leccion: 19, id_curso: 7,  tipo: "video", titulo: "Modelo OSI explicado",                 url: "https://edtech.pe/videos/redes-osi",           duracion_min: 70 },
  { id_leccion: 20, id_curso: 7,  tipo: "pdf",   titulo: "Comandos básicos Cisco IOS",           url: "https://edtech.pe/pdf/cisco-comandos.pdf" },
  { id_leccion: 21, id_curso: 7,  tipo: "quiz",  titulo: "Quiz: VLANs",                         preguntas: [{ pregunta: "¿En qué capa operan las VLANs?", opciones: ["Capa 1","Capa 2","Capa 3","Capa 4"], respuesta_correcta: 1 }] },
  // Curso 8 — Ciberseguridad
  { id_leccion: 22, id_curso: 8,  tipo: "video", titulo: "Reconocimiento con Nmap",              url: "https://edtech.pe/videos/nmap-recon",          duracion_min: 90 },
  { id_leccion: 23, id_curso: 8,  tipo: "pdf",   titulo: "Guía de Metasploit",                   url: "https://edtech.pe/pdf/metasploit.pdf" },
  { id_leccion: 24, id_curso: 8,  tipo: "quiz",  titulo: "Quiz: Post-explotación",               preguntas: [{ pregunta: "¿Qué es privilege escalation?", opciones: ["Instalar un exploit","Obtener permisos superiores a los asignados","Borrar logs","Escanear puertos"], respuesta_correcta: 1 }] },
  // Curso 9 — Python Data Science
  { id_leccion: 25, id_curso: 9,  tipo: "video", titulo: "Limpieza de datos con Pandas",         url: "https://edtech.pe/videos/pandas-limpieza",     duracion_min: 75 },
  { id_leccion: 26, id_curso: 9,  tipo: "pdf",   titulo: "Guía de Matplotlib y Seaborn",         url: "https://edtech.pe/pdf/visualizacion.pdf" },
  { id_leccion: 27, id_curso: 9,  tipo: "quiz",  titulo: "Quiz: Estadística básica",             preguntas: [{ pregunta: "¿Qué mide la desviación estándar?", opciones: ["El valor más frecuente","La dispersión de los datos","El valor central","La asimetría"], respuesta_correcta: 1 }] },
  // Curso 10 — Machine Learning
  { id_leccion: 28, id_curso: 10, tipo: "video", titulo: "Regresión lineal desde cero",          url: "https://edtech.pe/videos/ml-regresion",        duracion_min: 85 },
  { id_leccion: 29, id_curso: 10, tipo: "pdf",   titulo: "Random Forest explicado",              url: "https://edtech.pe/pdf/random-forest.pdf" },
  { id_leccion: 30, id_curso: 10, tipo: "quiz",  titulo: "Quiz: Evaluación de modelos",          preguntas: [{ pregunta: "¿Qué es el overfitting?", opciones: ["El modelo aprende bien en train pero falla en test","Modelo demasiado simple","Pocos datos","Modelo lento"], respuesta_correcta: 0 }] },
  // Curso 11 — Marketing
  { id_leccion: 31, id_curso: 11, tipo: "video", titulo: "SEO On-Page paso a paso",              url: "https://edtech.pe/videos/seo-onpage",          duracion_min: 60 },
  { id_leccion: 32, id_curso: 11, tipo: "pdf",   titulo: "Guía de Google Ads",                   url: "https://edtech.pe/pdf/google-ads.pdf" },
  { id_leccion: 33, id_curso: 11, tipo: "quiz",  titulo: "Quiz: Redes sociales",                 preguntas: [{ pregunta: "¿Qué es el engagement rate?", opciones: ["Número de seguidores","Porcentaje de interacciones sobre el alcance","Costo por clic","Número de publicaciones"], respuesta_correcta: 1 }] },
  // Curso 12 — Emprendimiento
  { id_leccion: 34, id_curso: 12, tipo: "video", titulo: "Cómo validar tu idea de negocio",      url: "https://edtech.pe/videos/validacion-idea",     duracion_min: 70 },
  { id_leccion: 35, id_curso: 12, tipo: "pdf",   titulo: "Plantilla de Lean Canvas",             url: "https://edtech.pe/pdf/lean-canvas.pdf" },
  { id_leccion: 36, id_curso: 12, tipo: "quiz",  titulo: "Quiz: Growth Hacking",                 preguntas: [{ pregunta: "¿Qué es el Product-Market Fit?", opciones: ["Cuando el producto se vende bien en el mercado objetivo","Cuando la app no tiene bugs","Cuando tienes inversión","Cuando lanzas el MVP"], respuesta_correcta: 0 }] }
]);


// ============================================================
// VERIFICACIÓN FINAL
// ============================================================
print("foro_hilos:      " + db.foro_hilos.countDocuments()      + " documentos");
print("progreso_alumno: " + db.progreso_alumno.countDocuments()  + " documentos");
print("materiales_curso:" + db.materiales_curso.countDocuments() + " documentos");
